#!/bin/bash
cd `dirname $0`
mkdir -p /tmp/pyghmi
cp -a * .git /tmp/pyghmi
cd /tmp/pyghmi
export PYEXEC=python3
export DSCARGS="--with-python2=True --with-python3=True"
if grep wheezy /etc/os-release; then
    # also it's old, use python2 instead of python3
    export PYEXEC=python
    export DSCARGS=""
fi
# If not PBR, use the setup.py.tmpl
$PYEXEC -c 'import pbr' || ./makesetup
VERSION=`$PYEXEC setup.py --version`
$PYEXEC setup.py sdist
py2dsc $DSCARGS dist/pyghmi-$VERSION.tar.gz
shopt -s extglob
cd deb_dist/!(*.orig)/
dpkg-buildpackage -rfakeroot -uc -us -i
cd -
rm -rf $(find deb_dist -mindepth 1 -maxdepth 1 -type d)
rm $1/*pyghmi*
cp deb_dist/* $1/
