#!/bin/bash
cd `dirname $0`
mkdir -p /tmp/aiohmi
cp -a * .git /tmp/aiohmi
cd /tmp/aiohmi
export PYEXEC=python3
export DSCARGS="--with-python2=True --with-python3=True"
if grep wheezy /etc/os-release; then
    # also it's old, use python2 instead of python3
    export PYEXEC=python
    export DSCARGS=""
fi
# If not PBR, use the setup.py.tmpl
sed -e 's/~/./' ./makesetup > ./makesetup.deb
chmod +x ./makesetup.deb
./makesetup.deb
#$PYEXEC -c 'import pbr' || ./makesetup
VERSION=`$PYEXEC setup.py --version`
$PYEXEC setup.py sdist
py2dsc $DSCARGS dist/aiohmi-$VERSION.tar.gz
shopt -s extglob
cd deb_dist/!(*.orig)/
dpkg-buildpackage -rfakeroot -uc -us -i
cd -
rm -rf $(find deb_dist -mindepth 1 -maxdepth 1 -type d)
rm $1/*aiohmi*
cp deb_dist/*.deb $1/
