- job:
    name: virtualbmc-tempest-ironic-ipmi-iscsi-pyghmi-src
    parent: virtualbmc-tempest-ironic-ipmi-iscsi
    required-projects:
      - x/pyghmi

- project:
    templates:
      - check-requirements
      - openstack-python-jobs
      - openstack-python3-ussuri-jobs
      - build-openstack-docs-pti
    check:
      jobs:
        - virtualbmc-tempest-ironic-ipmi-iscsi-pyghmi-src:
            voting: false
